Added time warning (6h)
rfresh2/ZenithProxy pull request #43
Opened 2023-10-16 09:24 UTC by UnzorZ

I created a time warning. It sends a message to the player 10 times and plays a sound (anvil place with slight pitch change so its not that loud). Also, it keeps sending messages every minute.

2023-10-16 22:17 UTC, MrFums commented
Hmm, doesnt seem to work for me?

2023-10-16 22:21 UTC, UnzorZ commented
what is exactly not working? are you testing it on 2b2t?

2023-10-16 22:55 UTC, rfresh2 requested changes

2023-10-16 22:55 UTC, rfresh2 commented on src/main/java/com/zenith/Proxy.java
> +            SCHEDULED_EXECUTOR_SERVICE.scheduleAtFixedRate(() -> {
extract the runnable being submitted here to a method

2023-10-16 22:55 UTC, rfresh2 commented on src/main/java/com/zenith/Proxy.java
> +                try {
add a check for if the account has prio or not in the runnable:

```
if (this.isPrio.orElse(false)) return; // skip the rest of the method and don't send any warnings
```

there's no 6hr kick for prio accounts

2023-10-16 22:55 UTC, rfresh2 commented on src/main/java/com/zenith/Proxy.java
> +                            for (int i=0; i<10; i++) { //Sends the message 10 times, so you don't miss it. It also sends it every minute from then
I think the amount of messages being sent is a bit excessive, I think just sending one every couple minutes would be more than enough.

Alternatively, we could set [the title, subtitle, or action bar texts](https://github.com/rfresh2/MCProtocolLib/tree/1.20/src/main/java/com/github/steveice10/mc/protocol/packet/ingame/clientbound/title). I'd personally prefer the action bar so its less obtrusive

2023-10-16 22:55 UTC, rfresh2 commented on src/main/java/com/zenith/Proxy.java
> +                                Proxy.getInstance().getActiveConnections().forEach(connection -> {
just sending this to the active player is fine: 

```
final ServerConnection playerConnection = this.currentPlayer.get();
if (playerConnection != null) // we have a player logged in, send any warning packets to this connection
  playerConnection.send(...)
```

And it'd be better to just check if there is an active player or not near the top of this runnable to skip most of the logic if not.

`if (!this.isConnected() || !this.hasActivePlayer()) return; // no active player - no need to do any in-game warnings`

2023-10-16 23:29 UTC, MrFums commented
> what is exactly not working? are you testing it on 2b2t?. It had been working for me for like 10 days or so

The "ding" noise is not coming through. Game sound maxed and what not, only thought could be the resource pack for some reason.

2023-10-17 20:36 UTC, UnzorZ commented
If you think i should change something else, please let me know ^^

2023-10-17 21:53 UTC, rfresh2 approved these changes

2023-10-17 21:55 UTC, merged

2023-10-17 21:55 UTC, rfresh2 commented
thanks!